name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_and_close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        run: npm run build -- --configuration production

      - name: Run unit tests
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Run E2E tests
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        run: npx ng e2e --configuration=production --watch=false --headless

      - name: Deploy to Azure Static Web Apps
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_WATER_092939D0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "dist/client/browser"
          api_location: ""
          output_location: "dist/client/"
          skip_app_build: true
          app_build_command: "npm run build -- --configuration production"
          api_build_command: ""
          app_artifact_location: "dist/client/"

      - name: Close Azure Static Web App preview
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        id: close_pull_request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_WATER_092939D0 }}
          action: close
